# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

#trigger:
#- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '7d9d909b-fce2-4aab-9761-396236f50c85'
  imageRepository01: 'python-back-api01'
  imageRepository02: 'python-back-api02'
  imageRepository03: 'python-back-api03'
  imageRepository04: 'python-back-api04'
  imageRepository05: 'python-back-api05'
  containerRegistry: 'michelsdev.azurecr.io'
  dockerfilePath01: '$(Build.SourcesDirectory)/back-api01/Dockerfile'
  dockerfilePath02: '$(Build.SourcesDirectory)/back-api02/Dockerfile'
  dockerfilePath03: '$(Build.SourcesDirectory)/back-api03/Dockerfile'
  dockerfilePath04: '$(Build.SourcesDirectory)/back-api04/Dockerfile'
  dockerfilePath05: '$(Build.SourcesDirectory)/back-api05/Dockerfile'
  tag: '$(Build.BuildId),latest'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build_backapi01
  displayName: Build and push stage - back-api01
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository01)
        dockerfile: $(dockerfilePath01)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
- stage: Build_backapi02
  displayName: Build and push stage - back-api02
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository02)
        dockerfile: $(dockerfilePath02)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
- stage: Build_backapi03
  displayName: Build and push stage - back-api03
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository03)
        dockerfile: $(dockerfilePath03)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
- stage: Build_backapi04
  displayName: Build and push stage - back-api04
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository04)
        dockerfile: $(dockerfilePath04)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
- stage: Build_backapi05
  displayName: Build and push stage - back-api05
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository05)
        dockerfile: $(dockerfilePath05)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Deploy_Containeres
  displayName: Deploy containeres
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure Michels(1)(fa3d8a7b-e927-4cbb-a1e1-ff6edfaa5eb5)'
        azureContainerRegistry: '{"loginServer":"michelsdev.azurecr.io", "id" : "/subscriptions/fa3d8a7b-e927-4cbb-a1e1-ff6edfaa5eb5/resourceGroups/rg-acr-devops/providers/Microsoft.ContainerRegistry/registries/michelsdev"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run services'